---
services:
  ntfy:
    image: binwiederhier/ntfy:v2.27.0
    container_name: ntfy
    command:
      - serve
    environment:
      NTFY_BASE_URL: https://${NTFY_HOSTNAME}
      NTFY_BEHIND_PROXY: "true"
      NTFY_CACHE_FILE: /var/cache/ntfy/cache.db
      NTFY_ATTACHMENT_CACHE_DIR: /var/cache/ntfy/attachments
      NTFY_AUTH_FILE: /var/lib/ntfy/user.db
      NTFY_AUTH_DEFAULT_ACCESS: deny-all
      NTFY_ENABLE_LOGIN: "true"
    volumes:
      - ntfy_cache:/var/cache/ntfy
      - ntfy_lib:/var/lib/ntfy
    networks:
      - proxy
    labels:
      traefik.enable: "true"
      traefik.http.routers.ntfy.rule: Host(`${NTFY_HOSTNAME}`)
      traefik.http.routers.ntfy.entrypoints: websecure
      traefik.http.routers.ntfy.tls: "true"
      traefik.http.routers.ntfy.tls.certresolver: letsencrypt
      traefik.http.services.ntfy.loadbalancer.server.port: "80"
    healthcheck:
      test: ["CMD-SHELL", "wget -q --tries=1 http://localhost:80/v1/health -O - | grep -Eo '\"healthy\"\\s*:\\s*true' || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    init: true

networks:
  proxy:
    external: true
    name: proxy

volumes:
  ntfy_cache:
    name: ntfy_cache
  ntfy_lib:
    name: ntfy_lib
