---
version: 2
updates:
  - package-ecosystem: pip
    directory: /ansible
    schedule:
      interval: weekly
  - package-ecosystem: terraform
    directory: terraform/aws
    schedule:
      interval: weekly
  - package-ecosystem: terraform
    directory: /terraform/cloudflare
    schedule:
      interval: weekly
  - package-ecosystem: terraform
    directory: /terraform/gcp-remindme
    schedule:
      interval: weekly
  - package-ecosystem: terraform
    directory: /terraform/gcp-weinbender-io
    schedule:
      interval: weekly
  - package-ecosystem: terraform
    directory: /terraform/mgmt
    schedule:
      interval: weekly
  - package-ecosystem: terraform
    directory: /terraform/proxmox
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns:
          - "*"
