---
name: Plan & Apply Terraform (all)

on:
  push:
    branches:
      - main
    paths:
      - terraform/**
  workflow_dispatch:
    inputs:
      apply:
        description: Apply Terraform
        type: boolean
        default: true


jobs:
  terraform:
    if: forgejo.ref == 'refs/heads/main'
    uses: ./.forgejo/workflows/terraform.yml
    with:
      components: all
      apply: ${{ forgejo.event_name == 'push' || inputs.apply }}
    secrets: inherit
