---
name: Plan or Apply Terraform

on:
  workflow_dispatch:
    inputs:
      component:
        description: Component to run Terraform against
        type: choice
        options:
          - mgmt
          - aws
          - gcp-remind-me
          - gcp-weinbender-io
          - cloudflare
        default: aws
      apply:
        description: Apply Terraform
        type: boolean
        default: false


jobs:
  terraform:
    if: forgejo.ref == 'refs/heads/main'
    uses: ./.forgejo/workflows/terraform.yml
    with:
      components: '["${{ inputs.component }}"]'
      apply: ${{ inputs.apply }}
    secrets: inherit
