- name: Ensure prerequisites for Docker
  ansible.builtin.package:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
  tags: [docker]
  become: true
  when: docker_install | default(false)

- name: Add Docker GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
    keyring: /usr/share/keyrings/docker-archive-keyring.gpg
  tags: [docker]
  become: true
  when: docker_install | default(false) and ansible_os_family == "Debian"

- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: >-
      deb [arch=amd64 signed-by=/usr/share/keyrings/
      docker-archive-keyring.gpg]
      https://download.docker.com/linux/ubuntu
      {{ ansible_distribution_release }} stable
    state: present
    filename: docker
  tags: [docker]
  become: true
  when: docker_install | default(false) and ansible_os_family == "Debian"

- name: Install Docker Engine
  ansible.builtin.package:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
  tags: [docker]
  become: true
  when: docker_install | default(false)

- name: Start and enable Docker
  ansible.builtin.systemd:
    name: docker
    enabled: true
    state: started
  tags: [docker]
  become: true
  when: docker_install | default(false) and systemd_available | default(true)

- name: Ensure homelab user in docker group
  ansible.builtin.user:
    name: "{{ homelab_user }}"
    groups: docker
    append: true
  tags: [docker, users]
  become: true
  when: docker_install | default(false)
