# Variables specific to the common role execution context.

# This file is for variables that are *not* defaults, but rather variables
# that are intended to be included via 'include_vars' and may be
# specific to a particular playbook run or environment.

# Example: If this role was used in a specific playbook that needed
# a different github user than the default, it could be overridden here.

# common_github_user: "another-user"
