---
services:
  traefik:
    image: traefik:v3.7
    container_name: traefik
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - >-
        traefik.http.routers.dashboard.rule=PathPrefix(`/dashboard`) ||
        PathPrefix(`/api`)
      - traefik.http.routers.dashboard.entrypoints=web
      - traefik.http.routers.dashboard.service=api@internal
    ports:
      - "80:80"
      - "443:443"
    command:
      - --certificatesresolvers.letsencrypt.acme.email=${ACME_EMAIL}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/dynamic:/etc/traefik/dynamic:ro
      - traefik_acme:/etc/traefik/acme
    environment:
      CF_DNS_API_TOKEN: ${CF_DNS_API_TOKEN}
    networks:
      - proxy

networks:
  proxy:
    name: proxy
    external: true

volumes:
  traefik_acme:
    name: traefik_acme
