workloads:
  hosts:
    jellyfin-lxc.tortoise-noodlefish.ts.net:
      ansible_host: jellyfin-lxc.tortoise-noodlefish.ts.net
      ansible_user: ansible
    traefik-lxc.tortoise-noodlefish.ts.net:
      ansible_host: traefik-lxc.tortoise-noodlefish.ts.net
      ansible_user: ansible
hypervisors:
  hosts:
    caba-host:
      ansible_host: 192.168.1.144
      ansible_user: root
    gateway-host:
      ansible_host: 192.168.14.134
      ansible_user: root
