workloads:
  vars:
    ansible_user: ansible
  hosts:
    jellyfin-lxc.tortoise-noodlefish.ts.net: null
    traefik-lxc.tortoise-noodlefish.ts.net:
      host_roles:
      - docker
    docker0-lxc.tortoise-noodlefish.ts.net:
      host_roles:
      - docker
hypervisors:
  vars:
    ansible_user: root
  hosts:
    caba-host:
      ansible_host: 192.168.1.144
    gateway-host:
      ansible_host: 192.168.14.134
