---
name: Plan & Apply Terraform (all)

on:
  push:
    branches:
      - main
    paths:
      - terraform/**
  workflow_dispatch:
    inputs:
      apply:
        description: Apply Terraform
        type: boolean
        default: true

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/terraform.yml
    with:
      components: all
      apply: ${{ github.event_name == 'push' || inputs.apply }}
      tailscale: true
    secrets: inherit
